# Базируемся на официальном образе Airflow
# Версию можно зафиксировать, например 2.10.1 с Python 3.11
FROM apache/airflow:2.10.1-python3.11

# Юзер root для установки системных зависимостей
USER root

# Переменные окружения Airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False \
    AIRFLOW__CORE__EXECUTOR=SequentialExecutor  \
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db

# Возврат к пользователю airflow
USER airflow

# Оптимизация слоев. Сначала зависимости, далее даги
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dags/ /opt/airflow/dags/

# volume для дагов, логов и метаданных БД
VOLUME ["/opt/airflow", "/opt/airflow/dags"]

# Стандартная точка входа Airflow
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/entrypoint"]
CMD ["standalone"]