# Базируемся на официальном образе Airflow
# Версию можно зафиксировать, например 2.10.1 с Python 3.11
FROM apache/airflow:2.10.1-python3.11

USER root

# Переменные окружения Airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False \
    AIRFLOW__CORE__EXECUTOR=SequentialExecutor  \
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db

# Копируем ваши DAG-и
COPY dags/ /opt/airflow/dags/

COPY entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

# Переходим под пользователем airflow (он уже создан в базовом образе)
USER airflow

# Сначала копируем requirements.txt в образ
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Команда по умолчанию – запуск webserver
# Можно переопределить на scheduler/worker через docker-compose или kubernetes
ENTRYPOINT ["/entrypoint.sh"]
