apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
  labels:
    app: demo-api
    tier: backend
    lab: hw4
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: demo-api
    tier: backend

